interface Zoo {
    fun addEmployee()
    fun deleteEmployee()
    fun removeEmployee(employee: Employee)
    fun addVisitor()
    fun removeVisitor(visitor: Visitor)
    fun getZooStatus()
    fun getEmployeeStatus()
    fun getVisitorStatus()
    fun makeAnimalSpeak()
    fun checkAnimalStatus()
    fun editInformation()
    fun addAnimal()
    fun addEnclosure()
    fun deleteEnclosure()
    var isPaused: Boolean
    fun updateAnimalStatus()
    fun shuffleAnimals()
    fun checkEnclosureStatus()
    fun buyFood()
    fun removeAnimal()
    fun addSpecialVisitor(visitor: Visitor)
    fun addSpecialEmployee(employee: Employee)
}
